apiVersion: apps/v1
kind: Deployment
metadata:
  name: zhouzhou
  namespace: dev
spec:
  selector:
    matchLabels:
      app: zhouzhou
  template:
    metadata:
      labels:
        app: zhouzhou
    spec:
      containers:
        - name: zhouzhou
          image: ${CICD_IMAGE}:${CICD_GIT_BRANCH}-${CICD_GIT_COMMIT}
          imagePullPolicy: Always
          resources:
            limits:
              memory: "2048Mi"
              cpu: "1024m"
          ports:
            - containerPort: 8089
      imagePullSecrets:
        - name: aliyun-registry

---

apiVersion: v1
kind: Service
metadata:
  name: zhouzhou
  namespace: dev
spec:
  selector:
    app: zhouzhou
  ports:
    - port: 8089
      targetPort: 30080
